Repository depromeet/17th-team1-client, pull requests merged in 2025-09, with the labels that each got.

#14 [GLB-36] 이미지 메타데이터 추출 기능 구현
  .github/workflows/deploy.yml
  Dockerfile
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/add_image_btn.svg
  src/app/api/geocode/route.ts
  src/app/api/places/route.ts
  src/app/image-metadata/page.tsx
  src/app/layout.tsx
  src/components/ReactGlobe.tsx
  src/components/image-metadata/FixedSaveButton.tsx
  src/components/image-metadata/GoogleMapsModal.tsx
  src/components/image-metadata/ImageMetadata.tsx
  src/components/image-metadata/ImageMetadataHeader.tsx
  src/components/image-metadata/LoadingOverlay.tsx
  src/lib/processFile.ts
  src/types/google-places.ts
  src/types/imageMetadata.ts
Labels: ✨ feat, 🛠️ refactor

#22 [GLB-107] 나라 선택 페이지 UI
  src/app/globals.css
  src/app/nation-select/page.tsx
  src/assets/icons/close.svg
  src/assets/icons/index.ts
  src/assets/icons/plus.svg
  src/components/common/badge.tsx
  src/components/common/button.tsx
  src/components/common/chip.tsx
  src/components/common/input.tsx
  src/types/.gitkeep
Labels: ✨ feat, 🎨 design

#25 [GLB-86, 90] 도시 API 연동(도시 검색, 인기 도시 조회)
  package-lock.json
  src/app/nation-select/page.tsx
  src/components/nation-select/CityItem.tsx
  src/components/nation-select/NationSelectClient.tsx
  src/components/nation-select/NationSelectFooter.tsx
  src/components/nation-select/NationSelectHeader.tsx
  src/components/nation-select/PopularCitiesList.tsx
  src/components/nation-select/SelectedCities.tsx
  src/config/env.ts
  src/hooks/useCitySearch.ts
  src/lib/README.md
  src/lib/apiClient.ts
  src/services/cityService.ts
  src/types/city.ts
  src/utils/countryFlagMapping.ts
Labels: ✨ feat

#29 [GLB-122] 소셜로그인 기존유저 판별 작업
  src/app/globe/page.tsx
  src/app/login/oauth/success/page.tsx
  src/app/login/oauth/success/route.ts
  src/app/login/page.tsx
  src/app/nation-select/page.tsx
  src/app/page.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/nation-select/NationSelectClient.tsx
  src/config/env.ts
  src/middleware.ts
  src/services/cityService.ts
  src/services/memberService.ts
  src/types/member.ts
  src/utils/cookies.ts
  src/utils/travelUtils.ts
Labels: ✨ feat, 🛠️ refactor, 🧹 chore

#30 [GLB-106] AI인사이트 API 작업
  src/app/globals.css
  src/components/nation-select/NationSelectFooter.tsx
  src/components/nation-select/PopularCitiesList.tsx
  src/hooks/useCitySearch.ts
  src/services/memberService.ts
  src/types/member.ts
Labels: ✨ feat, 🎨 design

#31 [GLB-120] 지구본 조회 api 연동, 로딩화면 추가 등
  public/assets/globe.png
  src/app/globe/page.tsx
  src/app/login/oauth/success/route.ts
  src/app/page.tsx
  src/components/globe/GlobeFooter.tsx
  src/components/globe/GlobeHeader.tsx
  src/components/globe/PatternSelector.tsx
  src/components/loading/GlobeLoading.tsx
  src/components/react-globe/CountryBasedGlobe.tsx
  src/components/react-globe/htmlElementRenderer.ts
  src/data/travelPatterns.ts
  src/hooks/useGlobeState.ts
  src/middleware.ts
  src/services/memberService.ts
  src/types/globe.ts
  src/types/member.ts
  src/types/travelPatterns.ts
  src/utils/autoFitUtils.ts
  src/utils/globeDataMapper.ts
Labels: ✨ feat, 🛠️ refactor

#33 [GLB-125] 배포 환경 로그인 리다이렉트 에러 해결
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🐞 bug

#37 fix: 특정 브라우저에서 카카오톡 로그인 시 whiteLabel 404 에러가 뜨는 현상 해결
  src/app/error/ErrorContent.tsx
  src/app/error/page.tsx
  src/app/globals.css
  src/app/login/oauth/success/route.ts
  src/app/login/page.tsx
  src/app/nation-select/page.tsx
  src/components/loading/GlobeLoading.tsx
  src/components/login/KakaoLoginButton.tsx
  src/components/nation-select/PopularCitiesList.tsx
  src/components/react-globe/htmlElementRenderer.ts
  src/config/env.ts
  src/hooks/useCitySearch.ts
  src/hooks/useGlobeState.ts
  src/middleware.ts
  src/services/cityService.ts
  src/services/memberService.ts
  src/types/member.ts
  src/utils/travelUtils.ts
Labels: 🐞 bug

#38 [GLB-127] 도시 검색 페이지 디자인 수정 2
  src/assets/icons/close.svg
  src/components/common/chip.tsx
  src/components/common/input.tsx
  src/components/nation-select/NationSelectClient.tsx
  src/components/nation-select/NationSelectFooter.tsx
  src/components/nation-select/SelectedCities.tsx
Labels: 🎨 design
